spring.application.name=attendancebackend

# Server (THIS IS THE FIX)
server.address=0.0.0.0
server.port=8080

# Database (NO CHANGE NEEDED)
spring.datasource.url=jdbc:mysql://localhost:3306/attendance_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Chaitu@1432

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
