#spring.application.name=attendancebackend
#
## Server
#server.address=0.0.0.0
#server.port=8080
#
## =========================
## DATABASE (SERVER DB)
## =========================
#spring.datasource.url=jdbc:mysql://sh00675.bluehost.com:3306/btvnmimy_attendance_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
#spring.datasource.username=btvnmimy_ocsadmin
#spring.datasource.password=sriadmin@12345
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jackson.serialization.fail-on-empty-beans=false
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.open-in-view=false
## Timezone
#spring.jackson.time-zone=Asia/Kolkata
#spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata



spring.application.name=attendancebackend

# Server (THIS IS THE FIX)
server.address=0.0.0.0
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/attendance_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=Chaitu@1432

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# ? ADD THESE TWO LINES FOR IST
spring.jackson.time-zone=Asia/Kolkata
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata